# https://starship.rs/config/

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'


format = """($cmd_duration\n)\\[$directory\\]\
( $shlvl\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$package\
$c\
$cmake\
$python\
$rust\
$env_var\
$custom\
$sudo\
\n)\
( $jobs\
$battery\
$status)\
$character
"""

add_newline = false

scan_timeout = 5

[directory]
style = 'bold purple'
format = '[$path]($style)[( $read_only)]($read_only_style)'
read_only_style = 'bold red'
read_only = 'RO '

[character]
success_symbol = '[\$](bold fg:244)'
error_symbol = '[\$](bold fg:244)'

[status]
disabled = false
symbol = 'X'

[package]
symbol = ''

[rust]
symbol = 'Rust '
